version: '3.8'

services:
  naukb:
    container_name: naukb
    image: avatarteam/naukb:${NAUKB_VERSION}
    ports:
      - "8083:8080"
    volumes:
      - ./.naukb:/opt/maxkb
      - ./admin:/opt/maxkb-app/ui/dist/admin
